### ISSUE TITLE
Add an off-by-default "unstable" feature

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/maud#187]
Add a Cargo feature named `unstable` to `maud`, which is off by default. This flag will be a no-op for now; it will be used in #188.

Add an "Unstable" build to the [Travis config](https://github.com/lambda-fairy/maud/blob/master/.travis.yml) which runs `cargo test` with the `unstable` feature turned on.

Change the "Benchmarks" build to enable the `unstable` feature as well (so that nightly-only optimizations are included).

# What about [`rustc_version`](https://crates.io/crates/rustc_version)?

It would be nice to use `rustc_version` to automatically toggle the feature flag based on whether the compiler is stable or nightly. However, as Maud doesn't build on stable yet, it would be impossible to test the flag if it worked this way. Using a manual flag instead lets us test the migration incrementally -- without having to execute it all at once. We can then slot in `rustc_version` when the migration is complete.

**Comment by SimonSapin** [comment]
Hi. I don’t use Maud, this issue caught my attention in [This Week In Rust](https://this-week-in-rust.org/blog/2020/06/10/this-week-in-rust-342/). I apologize if this unsolicited comment from someone not involved or affected is not welcome, feel free to let me know and hide or remove it.

I’m curious what is your reasoning for making `unstable` enabled by default. In other libraries it is often opt-in rather than opt-out. An app or project may choose to use Nightly for some specific reasons, exchanging access to some features for potential breakage when upgrading the toolchain, but that doesn’t mean they want to maximize potential breakage in all of their recursive dependencies (which could be tricky to update because of an intermediate dependency maintained by yet someone else).

Also, when a library crate is used more than once in a dependency graph its default features become increasingly difficult to disable because *all* crates depending on that library need to specify `default-features = false`. If any doesn’t, it’s implicitly requesting default features. And Cargo enables the union of request features (implicitly or not). This design of Cargo is consistent and makes some sense, but unfortunately it makes default features almost useless in my opinion.

**Comment by lambda-fairy** [comment]
Ah, I actually *did* know how Cargo features work (and have explained this exact issue to other people in the past...) but had a brain fart while writing the ticket 🤦‍♀️. I've changed it to off-by-default. Thanks for the correction!

**Comment by berwyn** [comment]
Would you mind if I took a stab at this? I've a project where I'd love to use Maud on stable so this is of special interest to me :)
