### ISSUE TITLE
Alias elements and attributes?

### ISSUE THREAD

**Issue by IronOxidizer** [lambda-fairy/maud#229]
I'm working with hand-minimized HTML/CSS and using single letter `.class` and `#id` names is rather inconvenient. Is there a way to alias elements along with their attributes? At the moment, I'm doing the following but it's not a perfect solution since I still have to include the element specifier otherwise maud wouldn't begin the block scope.

```rust
const DI_CONTENT_WRAPPER: PreEscaped<&'static str> = PreEscaped("div#cw");

...

fn my_func() -> Markup {
    html! {
        p#(DI_CONTENT_WRAPPER) {
            "My content"
        }
    }
}
```

Ideally I would be able to do the following:

```rust
const DI_CONTENT_WRAPPER: PreEscaped<&'static str> = PreEscaped("div#cw");

...

fn my_func() -> Markup {
    html! {
        (DI_CONTENT_WRAPPER) {
            "My content"
        }
    }
}
```

**Comment by lambda-fairy** [comment]
Hi @IronOxidizer! Unfortunately I can't think of a good way to express that either. Maud's design revolves around the macro having full visibility into the structure of the HTML. While the element name & attributes could be made dynamic, that feels like it'll complicate the implementation quite a bit, especially w.r.t. context-aware escaping (#181).

Declaring `DI_CONTENT_WRAPPER` as a macro could work. But since macro expansion happens outside-in, you'll need to do some elaborate hacks (search for "eager macro expansion" or ["tt-call"](https://github.com/dtolnay/tt-call)) to make that possible.

Have you considered passing the content as a parameter as well?

```rust
fn my_func(content: Markup) -> Markup {
    html! {
        p#cw { (content) }
    }
}
```

**Comment by IronOxidizer** [comment]
Yeah, seems like a really difficult design challenge.

I hadn't thought of making a simple wrapper function, for my purposes it should be good enough. Thanks!
