### ISSUE TITLE
`<|` add a scope operator to avoid nested parentheses

### ISSUE THREAD

**Issue by Piping** [lambda-fairy/maud#234]
Hi,

As `maud` become my primary way to write html in rust, one ergonomic issues about converting standard html format to maud is to add `{ }` for every nested block. In the end, I would have a block of html ends with `}}}}}}`.

Is it possible to have a pipe-like operator that add a new nested scope? e.g `<|` that create a scope with only **single** element.

So I would have this sample code look like this
```rust
html! {
        div class="container mx-auto px-6 pt-10 pb-6" {
          div class="flex flex-wrap" {
            @for (idx,section) in footer_setions.iter().enumerate() {
              div class="w-full sm:w-1/4 text-center sm:text-left" {
                h5 class="uppercase mb-6 font-bold" { (section.0) }
                ul class="mb-4" {
                  @for name in footer_setions[idx].1 {
                    li class="mt-2" {
                       a href="#" class="hover:underline text-gray-600 hover:text-orange-500" 
                       { (name) }
                    }
                  }
        } } } } }
}
```
into
```rust
html! {
        div class="container mx-auto px-6 pt-10 pb-6"  <|
           div class="flex flex-wrap"  <|
            @for (idx,section) in footer_setions.iter().enumerate() <|
              div class="w-full sm:w-1/4 text-center sm:text-left" {
                h5 class="uppercase mb-6 font-bold" { (section.0) }
                ul class="mb-4" <|
                  @for name in footer_setions[idx].1 <|
                    li class="mt-2"  <|
                     a href="#" class="hover:underline text-gray-600 hover:text-orange-500" { (name) }
              }//div
} //html
```

Thanks!!

**Comment by lambda-fairy** [comment]
Thanks for the suggestion.

I'm hesitant to add something like this, because:

- There's nothing in Rust or HTML that looks like `<|`, so this will eat into the ["strangeness budget"](https://steveklabnik.com/writing/the-language-strangeness-budget).
- The syntax is already more concise than HTML, because you don't need to repeat the name in the end tag (`</div>`). So I don't feel the need to shorten it further.

For these reasons I will close this request. Feel free to reopen if you'd like to discuss further!
