### ISSUE TITLE
Formatting html! macro invocation

### ISSUE THREAD

**Issue by diegopy** [lambda-fairy/maud#263]
Is there any way to automatically format uses of the html! macro? rustfmt ignores it, and I'm not sure it would do a good job in any case.
Thanks!

**Comment by lambda-fairy** [comment]
I'm not aware of one. Rustfmt macro support has been a feature request for a long time (see rust-lang/rustfmt#8, rust-lang/rustfmt#3705) without any movement in that space.

**Comment by lambda-fairy** [comment]
Closing this as I don't think we can action this from the Maud side. Feel free to reopen if you have any concerns!

**Comment by maxcountryman** [comment]
I've been wondering about this too as I'm using maud more: it's difficult and imprecise to do by hand and yet it's crucial for readability even with excellent abstractions with techniques like partials.

It actually seems pretty challenging for rustfmt to tackle (altho I agree that would be nice more generally) because macro syntax varies from valid Rust code.
