### ISSUE TITLE
Documentation question: unclear on toggles

### ISSUE THREAD

**Issue by xpe** [lambda-fairy/maud#389]
> Toggles: [foo]
>
> Use [foo] syntax to show or hide something based on a boolean expression foo.
>
> This works on empty attributes:

From reading the [documentation on toggles](https://maud.lambda.xyz/splices-toggles.html), it *seems* like it would control the rendering of an element. (In my experience, I don't recall seeing a 'toggle' feature in libraries along the lines of Maud; typically in other libraries I use conditional logic for this purpose.)

Or is it something else?

[This issue](https://github.com/lambda-fairy/maud/issues/85) suggests it is something else. (If so, the documentation's wording could be made clearer for sure.)

**Comment by FallBackITA27** [comment]
bump

**Comment by puetzp** [comment]
The documentation states that this toggles _attributes_ and _classes_ on elements. It does not toggle the element itself with its respective attributes and elements. You are right that if you wanted to display an element on some conditional logic would use `@if` .

I have not been using maud for long, but I think the documentation is quite clear on that part.

**Comment by puetzp** [comment]
Thank you for your thorough excourse on this topic. Since I (admittedly) do not have the same philosophical bent, I am going to take the easy route and basically agree with everything you are saying!

You are right in that it is vital for the documentation to highlight and explain unambiguously how a feature works. I also agree that the "toggling of attributes and classes on elements" feature is a prime example where precisely worded documentation is important since it is such a fundamental feature of this library and one that is, in my opinion, very well implemented and incredibly useful.

I understand that just because I do not have an issue interpreting the documentation does not necessarily mean that this is the case for  _everyone_.

That being said I think a Pull Request that improves the explanation of this feature in the documentation will be more than welcome and appreciated by the maintainer(s)! And it will surely avoid confusion in future users who learn how to use maud as well.

**Comment by lambda-fairy** [comment]
Hi all, I haven't read the full discussion, but I'm happy to review a PR that improves the docs.

**Comment by puetzp** [comment]
Sorry, opened the PR in the wrong repository ... fixed.
