### ISSUE TITLE
Feature request: break and continue

### ISSUE THREAD

**Issue by twilight-flower** [lambda-fairy/maud#433]
Currently, Maud implements large fractions of loop-related control-flow, but has no way (that I've managed to find) to invoke `break` or `continue` from within a loop in Maud. This leads to limitations on loop-structure, compared with what can be done with loops outside of Maud. Is it practical to add support for those? If so, I'd like to request that, likely involving keywords-within-Maud `@break` and `@continue` in order to hold to the locally-usual syntax-pattern.

**Comment by lambda-fairy** [comment]
Thanks for the suggestion.

I don't think this will work. Consider what happens if you `break` from inside a nested element. If you implement that naively, you'll skip past the code that emits the end tag.

Even if we could make this work, I don't think this is worthwhile. We should minimize the logic in our templates. Anything that requires a `break` or `continue` can be more cleanly expressed in a pre-processing step or iterator adapter.
