### ISSUE TITLE
Compile-time HTML validation

### ISSUE THREAD

**Issue by DemiMarie** [lambda-fairy/maud#89]
Maud should check at compile-time that any produced HTML is syntactically valid, unless the `PreEscaped` filter is used.

**Comment by lfairy** [comment]
What do you mean by syntactically valid?

That can range from simple checks (e.g. check that element and attribute names are in a pre-defined list) to complex ones (e.g. using phantom types to statically enforce the content model).

See also #66.

**Comment by DemiMarie** [comment]
Enforcing the content model.

**Comment by lfairy** [comment]
Sure, let's work through this.

Consider the following example, spread across two crates:

```rust
// foo.rs

pub fn foo() -> Markup {
    html! {
        title "title!"
    }
}
```

```rust
// bar.rs

extern crate foo;

pub fn bar() -> Markup {
    html! {
        table (foo::foo())
    }
}
```

This is clearly violating the content model, because you cannot have a `<title>` tag inside of a `<table>`.

But how would Maud figure that out?

**Comment by lfairy** [comment]
Also, consider that HTML's content categories [overlap and include each other](https://html.spec.whatwg.org/multipage/dom.html#kinds-of-content).

To express those relationships within Rust's type system, we would at least need subtyping to make this ergonomic.

**Comment by DemiMarie** [comment]
Could this be done with type-level computation?

**Comment by lfairy** [comment]
To be honest I haven't thought much about that.

If you can write up a concrete proposal then I'd be happy to review it.

**Comment by Korvox** [comment]
I was writing some SQL and came across postgres-rust's excellent `sql!` macro from its postgres-macros crate and thought something like that could work with html too.

Basically, instead of trying to write an html lexer from scratch, use HTML Tidy or another html validator through FFI. It could go so far as to just be a generic tidy crate that provides a macro that takes stringly html and spits out Tidy error codes. Maud could just use that with a feature flag or via an extra macro definition like `tidy!{html!{...}}`. 

That being said, right now I'm just writing out my `Markup` and running it through tidy so you can already get 90% of the way there already with a little build scripting. Just having a nice macro to do it for you would be more convenient.

**Comment by lambda-fairy** [comment]
I'm going to go ahead and close this.

The security aspect will be covered by context-aware escaping (#181), and I don't think what's left is compelling enough to devote heavy type machinery to solving.
